sig_country_name = {'AF' :  'Afeganistão',
               'CL' :  'Chile',
               'ZA' :  'Africa do Sul',
               'CN' :  'China',
               'AL' :  'Albânia',
               'CY' :  'Chipre',
               'DE' :  'Alemanha',
               'CO' :  'Colômbia',
               'AD' :  'Andorra',
               'KM' :  'Comores',
               'AO' :  'Angola',
               'CG' :  'Congo',
               'AI' :  'Anguilla',
               'CI' :  'Costa do Marfim',
               'AQ' :  'Antartica',
               'CR' :  'Costa Rica',
               'AG' :  'Antígua e Barbuda',
               'HR' :  'Croácia',
               'AN' :  'Antilhas Holandesas',
               'CU' :  'Cuba',
               'SA' :  'Arábia Saudita',
               'DK' :  'Dinamarca',
               'DZ' :  'Argélia',
               'DJ' :  'Djibuti',
               'AR' :  'Argentina',
               'DM' :  'Dominica',
               'AM' :  'Armênia',
               'EG' :  'Egito',
               'AW' :  'Aruba',
               'SV' :  'El Salvador',
               'AU' :  'Austrália',
               'AE' :  'Emirados Árabes Unidos',
               'AT' :  'Áustria',
               'EC' :  'Equador',
               'AZ' :  'Azerbaidjão',
               'ER' :  'Eritréia',
               'BS' :  'Bahamas',
               'EM' :  'Escritório para Harmonização no Mercado Interno',
               'BD' :  'Bangladesh',
               'SK' :  'Eslováquia',
               'BB' :  'Barbados',
               'SI' :  'Eslovenia',
               'BH' :  'Bareine',
               'ES' :  'Espanha',
               'BY' :  'Belarus',
               'US' :  'Estados Unidos da América',
               'BE' :  'Bélgica',
               'EE' :  'Estônia',
               'BZ' :  'Belize',
               'ET' :  'Etiópia',
               'BX' :  'Benelux',
               'RU' :  'Federação Russa',
               'BJ' :  'Benin',
               'FJ' :  'Fiji',
               'BM' :  'Bermudas',
               'PH' :  'Filipinas',
               'BO' :  'Bolívia',
               'FI' :  'Finlândia',
               'BA' :  'Bósnia e Herzegóvina',
               'FR' :  'França',
               'BW' :  'Botswana',
               'GA' :  'Gabão',
               'BR' :  'Brasil',
               'GM' :  'Gambia',
               'BG' :  'Bulgária',
               'GE' :  'Geórgia',
               'BN' :  'Brunei Darussalam',
               'GH' :  'Gana',
               'BF' :  'Burkina Faso',
               'GS' :  'Geórgia do Sul e Ilhas Sandwich do Sul',
               'BI' :  'Burundi',
               'GI' :  'Gibraltar',
               'BT' :  'Butão',
               'GD' :  'Granada',
               'CV' :  'Cabo Verde',
               'GR' :  'Grécia',
               'CM' :  'Camarões',
               'GL' :  'Groenlândia',
               'KH' :  'Camboja',
               'GP' :  'Guadalupe',
               'CA' :  'Canadá',
               'GU' :  'Guam',
               'QA' :  'Catar',
               'GT' :  'Guatemala',
               'KZ' :  'Cazaquistão',
               'GY' :  'Guiana',
               'TD' :  'Chade',
               'GN' :  'Guine',
               'GW' :  'Guiné Bissau',
               'JO' :  'Jordânia',
               'GQ' :  'Guine Equatorial',
               'KI' :  'Kiribati',
               'HT' :  'Haiti',
               'KW' :  'Kuwait',
               'NL' :  'Holanda',
               'LA' :  'Laos',
               'HN' :  'Honduras',
               'LS' :  'Lesoto',
               'HK' :  'Hong-Kong',
               'LV' :  'Letônia',
               'HU' :  'Hungria',
               'LB' :  'Líbano',
               'YE' :  'Iêmen',
               'LR' :  'Libéria',
               'BV' :  'Ilha Bouvet',
               'LY' :  'Líbia',
               'IM' :  'Ilha do Homem',
               'LI' :  'Liechtenstein',
               'CX' :  'Ilha Natal',
               'LT' :  'Lituânia',
               'NF' :  'Ilha Norfalk',
               'LU' :  'Luxemburgo',
               'KY' :  'Ilhas Cayman',
               'MO' :  'Macau',
               'CC' :  'Ilhas Cocos',
               'MG' :  'Madagascar',
               'CK' :  'Ilhas Cook',
               'MY' :  'Malásia',
               'GG' :  'Ilhas do Canal',
               'MW' :  'Malawi',
               'FO' :  'Ilhas Faroe',
               'MV' :  'Maldivas',
               'HM' :  'Ilhas Heard e McDonald',
               'ML' :  'Mali',
               'FK' :  'Ilhas Malvinas',
               'MT' :  'Malta',
               'MP' :  'Ilhas Marianas do Norte',
               'MA' :  'Marrocos',
               'MH' :  'Ilhas Marshall',
               'MQ' :  'Martinica',
               'UM' :  'Ilhas Menores',
               'MU' :  'Maurício',
               'SB' :  'Ilhas Salomão',
               'MR' :  'Mauritânia',
               'TC' :  'Ilhas Turks e Caicos',
               'MX' :  'México',
               'VG' :  'Ilhas Virgens (Britânicas)',
               'MM' :  'Mianmá',
               'VI' :  'Ilhas Virgens (U.S.)',
               'FM' :  'Micronésia',
               'WF' :  'Ilhas Wallis e Futura',
               'MZ' :  'Moçambique',
               'IN' :  'India',
               'MC' :  'Mônaco',
               'ID' :  'Indonésia',
               'MN' :  'Mongólia',
               'IR' :  'Irã',
               'MS' :  'Mont Serrat',
               'IQ' :  'Iraque',
               'ME' :  'Montenegro',
               'IE' :  'Irlanda',
               'NA' :  'Namíbia',
               'IS' :  'Islândia',
               'NR' :  'Nauru',
               'IL' :  'Israel',
               'NP' :  'Nepal',
               'ID' :  'Indonésia',
               'NI' :  'Nicarágua',
               'IR' :  'Irã',
               'NE' :  'Níger',
               'IQ' :  'Iraque',
               'NG' :  'Nigéria',
               'IE' :  'Irlanda',
               'NO' :  'Noruega',
               'IS' :  'Islândia',
               'NC' :  'Nova Caledônia',
               'IL' :  'Israel',
               'NZ' :  'Nova Zelândia',
               'IT' :  'Itália',
               'OM' :  'Omã',
               'JM' :  'Jamaica',
               'OA' :  'Organização Africana de Propriedade Intelectual (OAPI)',
               'JP' :  'Japão',
               'WO' :  'Organização Mundial de Propriedade Intelectual – OMPI (WIPO)',
               'JE' :  'Jersey',
               'AP' :  'Organização Regional de Propriedade Industrial Africana',
               'PW' :  'Palau',
               'SE' :  'Suécia',
               'PA' :  'Panamá',
               'CH' :  'Suíça',
               'PG' :  'Papua Nova Guiné',
               'SR' :  'Suriname',
               'PK' :  'Paquistão',
               'SJ' :  'Svalbard e Jan Mayen',
               'PY' :  'Paraguai',
               'TJ' :  'Tadjiquistão',
               'PE' :  'Peru',
               'TH' :  'Tailândia',
               'PN' :  'Pitcairn',
               'TW' :  'Taiwan',
               'PF' :  'Polinésia Francesa',
               'TF' :  'Terras Austrais Francesas',
               'PL' :  'Polônia',
               'IO' :  'Territ.Britan.Oceano Índico',
               'PR' :  'Porto Rico',
               'PS' :  'Território Ocupado Palestino',
               'PT' :  'Portugal',
               'TL' :  'Timor-Leste',
               'KE' :  'Quênia',
               'TG' :  'Togo',
               'KG' :  'Quirguistão',
               'TK' :  'Tokelau',
               'GB' :  'Reino Unido',
               'TO' :  'Tonga',
               'CF' :  'República Centro Africana',
               'TT' :  'Trinidad e Tobago',
               'KR' :  'República da Coréia',
               'TN' :  'Tunísia',
               'MK' :  'República da Macedonia',
               'TM' :  'Turcomenistão',
               'MD' :  'República da Moldova',
               'TR' :  'Turquia',
               'CD' :  'República Dem. Do Congo',
               'TV' :  'Tuvalu',
               'DO' :  'República Dominicana',
               'UA' :  'Ucrânia',
               'KP' :  'República Pop. Dem. da Coreia',
               'UG' :  'Uganda',
               'CZ' :  'República Tcheca',
               'UY' :  'Uruguai',
               'TZ' :  'República Unida da Tanzânia',
               'UZ' :  'Uzbequistão',
               'RE' :  'Reunião',
               'VU' :  'Vanuatu',
               'RO' :  'Romênia',
               'VA' :  'Vaticano',
               'RW' :  'Ruanda',
               'VE' :  'Venezuela',
               'EH' :  'Saara Ocidental',
               'VN' :  'Vietnã',
               'PM' :  'Saint Pierre e Miquelon',
               'YU' :  'Yugoslávia',
               'AS' :  'Samoa Americana',
               'ZR' :  'Zaire',
               'WS' :  'Samoa Ocidental',
               'ZM' :  'Zâmbia',
               'SH' :  'Santa Helena',
               'ZW' :  'Zimbábue',
               'LC' :  'Santa Lúcia',
               'KN' :  'São Cristovão e Nevis',
               'SM' :  'São Marino',
               'ST' :  'São Tomé e Príncipe',
               'VC' :  'São Vicente e Granadinas',
               'SN' :  'Senegal',
               'SL' :  'Serra Leoa',
               'RS' :  'Sérvia',
               'SC' :  'Seychelles',
               'SG' :  'Singapura',
               'SY' :  'Síria',
               'SO' :  'Somália',
               'LK' :  'Sri Lanka',
               'SZ' :  'Suazilândia',
               'SD' :  'Sudão'}

name_country_sig = { 'Afeganistão': 'AF',
               'Chile': 'CL',
               'Africa do Sul': 'ZA',
               'China': 'CN',
               'Albânia': 'AL',
               'Chipre': 'CY',
               'Alemanha': 'DE',
               'Colômbia': 'CO',
               'Andorra': 'AD',
               'Comores': 'KM',
               'Angola': 'AO',
               'Congo': 'CG',
               'Anguilla': 'AI',
               'Costa do Marfim': 'CI',
               'Antartica': 'AQ',
               'Costa Rica': 'CR',
               'Antígua e Barbuda': 'AG',
               'Croácia': 'HR',
               'Antilhas Holandesas': 'AN',
               'Cuba': 'CU',
               'Arábia Saudita': 'SA',
               'Dinamarca': 'DK',
               'Argélia': 'DZ',
               'Djibuti': 'DJ',
               'Argentina': 'AR',
               'Dominica': 'DM',
               'Armênia': 'AM',
               'Egito': 'EG',
               'Aruba': 'AW',
               'El Salvador': 'SV',
               'Austrália': 'AU',
               'Emirados Árabes Unidos': 'AE',
               'Áustria': 'AT',
               'Equador': 'EC',
               'Azerbaidjão': 'AZ',
               'Eritréia': 'ER',
               'Bahamas': 'BS',
               'Escritório para Harmonização no Mercado Interno': 'EM',
               'Bangladesh': 'BD',
               'Eslováquia': 'SK',
               'Barbados': 'BB',
               'Eslovenia': 'SI',
               'Bareine': 'BH',
               'Espanha': 'ES',
               'Belarus': 'BY',
               'Estados Unidos da América': 'US',
               'Bélgica': 'BE',
               'Estônia': 'EE',
               'Belize': 'BZ',
               'Etiópia': 'ET',
               'Benelux': 'BX',
               'Federação Russa': 'RU',
               'Benin': 'BJ',
               'Fiji': 'FJ',
               'Bermudas': 'BM',
               'Filipinas': 'PH',
               'Bolívia': 'BO',
               'Finlândia': 'FI',
               'Bósnia e Herzegóvina': 'BA',
               'França': 'FR',
               'Botswana': 'BW',
               'Gabão': 'GA',
               'Brasil': 'BR',
               'Gambia': 'GM',
               'Bulgária': 'BG',
               'Geórgia': 'GE',
               'Brunei Darussalam': 'BN',
               'Gana': 'GH',
               'Burkina Faso': 'BF',
               'Geórgia do Sul e Ilhas Sandwich do Sul': 'GS',
               'Burundi': 'BI',
               'Gibraltar': 'GI',
               'Butão': 'BT',
               'Granada': 'GD',
               'Cabo Verde': 'CV',
               'Grécia': 'GR',
               'Camarões': 'CM',
               'Groenlândia': 'GL',
               'Camboja': 'KH',
               'Guadalupe': 'GP',
               'Canadá': 'CA',
               'Guam': 'GU',
               'Catar': 'QA',
               'Guatemala': 'GT',
               'Cazaquistão': 'KZ',
               'Guiana': 'GY',
               'Chade': 'TD',
               'Guine': 'GN',
               'Guiné Bissau': 'GW',
               'Jordânia': 'JO',
               'Guine Equatorial': 'GQ',
               'Kiribati': 'KI',
               'Haiti': 'HT',
               'Kuwait': 'KW',
               'Holanda': 'NL',
               'Laos': 'LA',
               'Honduras': 'HN',
               'Lesoto': 'LS',
               'Hong-Kong': 'HK',
               'Letônia': 'LV',
               'Hungria': 'HU',
               'Líbano': 'LB',
               'Iêmen': 'YE',
               'Libéria': 'LR',
               'Ilha Bouvet': 'BV',
               'Líbia': 'LY',
               'Ilha do Homem': 'IM',
               'Liechtenstein': 'LI',
               'Ilha Natal': 'CX',
               'Lituânia': 'LT',
               'Ilha Norfalk': 'NF',
               'Luxemburgo': 'LU',
               'Ilhas Cayman': 'KY',
               'Macau': 'MO',
               'Ilhas Cocos': 'CC',
               'Madagascar': 'MG',
               'Ilhas Cook': 'CK',
               'Malásia': 'MY',
               'Ilhas do Canal': 'GG',
               'Malawi': 'MW',
               'Ilhas Faroe': 'FO',
               'Maldivas': 'MV',
               'Ilhas Heard e McDonald': 'HM',
               'Mali': 'ML',
               'Ilhas Malvinas': 'FK',
               'Malta': 'MT',
               'Ilhas Marianas do Norte': 'MP',
               'Marrocos': 'MA',
               'Ilhas Marshall': 'MH',
               'Martinica': 'MQ',
               'Ilhas Menores': 'UM',
               'Maurício': 'MU',
               'Ilhas Salomão': 'SB',
               'Mauritânia': 'MR',
               'Ilhas Turks e Caicos': 'TC',
               'México': 'MX',
               'Ilhas Virgens (Britânicas)': 'VG',
               'Mianmá': 'MM',
               'Ilhas Virgens (U.S.)': 'VI',
               'Micronésia': 'FM',
               'Ilhas Wallis e Futura': 'WF',
               'Moçambique': 'MZ',
               'India': 'IN',
               'Mônaco': 'MC',
               'Indonésia': 'ID',
               'Mongólia': 'MN',
               'Irã': 'IR',
               'Mont Serrat': 'MS',
               'Iraque': 'IQ',
               'Montenegro': 'ME',
               'Irlanda': 'IE',
               'Namíbia': 'NA',
               'Islândia': 'IS',
               'Nauru': 'NR',
               'Israel': 'IL',
               'Nepal': 'NP',
               'Indonésia': 'ID',
               'Nicarágua': 'NI',
               'Irã': 'IR',
               'Níger': 'NE',
               'Iraque': 'IQ',
               'Nigéria': 'NG',
               'Irlanda': 'IE',
               'Noruega': 'NO',
               'Islândia': 'IS',
               'Nova Caledônia': 'NC',
               'Israel': 'IL',
               'Nova Zelândia': 'NZ',
               'Itália': 'IT',
               'Omã': 'OM',
               'Jamaica': 'JM',
               'Organização Africana de Propriedade Intelectual (OAPI)': 'OA',
               'Japão': 'JP',
               'Organização Mundial de Propriedade Intelectual – OMPI (WIPO)': 'WO',
               'Jersey': 'JE',
               'Organização Regional de Propriedade Industrial Africana': 'AP',
               'Palau': 'PW',
               'Suécia': 'SE',
               'Panamá': 'PA',
               'Suíça': 'CH',
               'Papua Nova Guiné': 'PG',
               'Suriname': 'SR',
               'Paquistão': 'PK',
               'Svalbard e Jan Mayen': 'SJ',
               'Paraguai': 'PY',
               'Tadjiquistão': 'TJ',
               'Peru': 'PE',
               'Tailândia': 'TH',
               'Pitcairn': 'PN',
               'Taiwan': 'TW',
               'Polinésia Francesa': 'PF',
               'Terras Austrais Francesas': 'TF',
               'Polônia': 'PL',
               'Territ.Britan.Oceano Índico': 'IO',
               'Porto Rico': 'PR',
               'Território Ocupado Palestino': 'PS',
               'Portugal': 'PT',
               'Timor-Leste': 'TL',
               'Quênia': 'KE',
               'Togo': 'TG',
               'Quirguistão': 'KG',
               'Tokelau': 'TK',
               'Reino Unido': 'GB',
               'Tonga': 'TO',
               'República Centro Africana': 'CF',
               'Trinidad e Tobago': 'TT',
               'República da Coréia': 'KR',
               'Tunísia': 'TN',
               'República da Macedonia': 'MK',
               'Turcomenistão': 'TM',
               'República da Moldova': 'MD',
               'Turquia': 'TR',
               'República Dem. Do Congo': 'CD',
               'Tuvalu': 'TV',
               'República Dominicana': 'DO',
               'Ucrânia': 'UA',
               'República Pop. Dem. da Coreia': 'KP',
               'Uganda': 'UG',
               'República Tcheca': 'CZ',
               'Uruguai': 'UY',
               'República Unida da Tanzânia': 'TZ',
               'Uzbequistão': 'UZ',
               'Reunião': 'RE',
               'Vanuatu': 'VU',
               'Romênia': 'RO',
               'Vaticano': 'VA',
               'Ruanda': 'RW',
               'Venezuela': 'VE',
               'Saara Ocidental': 'EH',
               'Vietnã': 'VN',
               'Saint Pierre e Miquelon': 'PM',
               'Yugoslávia': 'YU',
               'Samoa Americana': 'AS',
               'Zaire': 'ZR',
               'Samoa Ocidental': 'WS',
               'Zâmbia': 'ZM',
               'Santa Helena': 'SH',
               'Zimbábue': 'ZW',
               'Santa Lúcia': 'LC',
               'São Cristovão e Nevis': 'KN',
               'São Marino': 'SM',
               'São Tomé e Príncipe': 'ST',
               'São Vicente e Granadinas': 'VC',
               'Senegal': 'SN',
               'Serra Leoa': 'SL',
               'Sérvia': 'RS',
               'Seychelles': 'SC',
               'Singapura': 'SG',
               'Síria': 'SY',
               'Somália': 'SO',
               'Sri Lanka': 'LK',
               'Suazilândia': 'SZ',
               'Sudão': 'SD'}